CC = gcc
CFLAGS = -Wall -pedantic
LDFLAGS = -lrt
BTRACKFLAGS = -DUSE_KISS_FFT

all: main.o BTrack.o OnsetDetectionFunction.o kiss_fft.o samplerate.o src_sinc.o src_zoh.o src_linear.o
	$(CC) -o $@ $< $(CFLAGS) $(LDFLAGS)
	
main.o: main.cpp BTrack/BTrack.h
	$(CC) -o $@ $< $(CFLAGS) $(LDFLAGS)
	
BTrack.o: BTrack/BTrack.h BTrack/BTrack.cpp BTrack/OnsetDetectionFunction.h BTrack/CircularBuffer.h BTrack/src/samplerate.h
	$(CC) -o $@ $< $(CFLAGS) $(BTRACKFLAGS)
	
OnsetDetectionFunction.o: BTrack/OnsetDetectionFunction.cpp BTrack/OnsetDetectionFunction.h
	$(CC) -o $@ $< $(CFLAGS) $(BTRACKFLAGS)
	
kiss_fft.o: BTrack/kiss_fft/kiss_fft.c BTrack/kiss_fft/kiss_fft.h BTrack/kiss_fft/_kiss_fft_guts.h
	$(CC) -o $@ $< $(CFLAGS)

samplerate.o: BTrack/src/samplerate.h BTrack/src/samplerate.c BTrack/src/common.h
	$(CC) -o $@ $< $(CFLAGS)

src_sinc.o: BTrack/src/src_sinc.c BTrack/src/common.h
	$(CC) -o $@ $< $(CFLAGS)

src_zoh.o: BTrack/src/src_zoh.c BTrack/src/common.h
	$(CC) -o $@ $< $(CFLAGS)

src_linear.o: BTrack/src/src_linear.c BTrack/src/common.h
	$(CC) -o $@ $< $(CFLAGS)

clean: 
	rm *.o

